# Generated by Django 5.2.8 on 2026-01-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_contactmessage_delete_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the image if hosted externally'),
        ),
    ]
